/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VulnerabilitiesRouteImport } from './routes/vulnerabilities'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as ProxyRouteImport } from './routes/proxy'
import { Route as IndexRouteImport } from './routes/index'

const VulnerabilitiesRoute = VulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyRoute = ProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proxy': typeof ProxyRoute
  '/scope': typeof ScopeRoute
  '/studio': typeof StudioRoute
  '/targets': typeof TargetsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proxy': typeof ProxyRoute
  '/scope': typeof ScopeRoute
  '/studio': typeof StudioRoute
  '/targets': typeof TargetsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proxy': typeof ProxyRoute
  '/scope': typeof ScopeRoute
  '/studio': typeof StudioRoute
  '/targets': typeof TargetsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proxy'
    | '/scope'
    | '/studio'
    | '/targets'
    | '/vulnerabilities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proxy' | '/scope' | '/studio' | '/targets' | '/vulnerabilities'
  id:
    | '__root__'
    | '/'
    | '/proxy'
    | '/scope'
    | '/studio'
    | '/targets'
    | '/vulnerabilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProxyRoute: typeof ProxyRoute
  ScopeRoute: typeof ScopeRoute
  StudioRoute: typeof StudioRoute
  TargetsRoute: typeof TargetsRoute
  VulnerabilitiesRoute: typeof VulnerabilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vulnerabilities': {
      id: '/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof VulnerabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy': {
      id: '/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProxyRoute: ProxyRoute,
  ScopeRoute: ScopeRoute,
  StudioRoute: StudioRoute,
  TargetsRoute: TargetsRoute,
  VulnerabilitiesRoute: VulnerabilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
